version: "3"

services:
  be:
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/controller
    command: >
      sh -c "python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn controller.wsgi:application --bind 0.0.0.0:8888"

    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  commandmanager:
    build:
      context: .
    volumes:
      - ./:/controller
    command: >
      sh -c "python manage.py commandmanager"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
  fe:
    build: /tmp/Controller_FE/controller-front
    container_name: conrtoller-fe
    expose:
      - 8080
    ports:
      - "8080:8080"
