# Generated by Django 3.0.8 on 2020-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commandname', models.CharField(blank=True, max_length=120)),
                ('os', models.CharField(max_length=32)),
            ],
        ),
    ]
