# Generated by Django 3.0.8 on 2020-09-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200924_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
